### PR TITLE
Sounds

### PR DESCRIPTION
**Pull request by benjaminreid**
Get some basic sounds playing from clicking on the pads.

### CODE REVIEW

**Comment by benjaminreid** [comment]
@daviddarnes While this not using the MIDI API yet, it does load in 3 sounds, assign them to pads then let you click them to play the sound. After hooking up the MIDI controller, the MVP should nearly be there.

🔉

**Comment by daviddarnes** [comment]
Amazing work man, I wish we could set aside some time to work on this in the same space

**Comment by daviddarnes** [comment]
@nouveller I need to get on this don't I, sorry 😞 . Is it still worth contributing to?

**Comment by benjaminreid** [comment]
I'd totally forgot it existed until you just commented on it, haha. We should use it for the next podcast, whether that's this Thursday or next.

I can't quite remember what state it is in. But it could do with simple styles I suppose. More so when there is some more UI.

**Comment by benjaminreid** [comment]
I've merged, feel free to add any styling to `master`. I don't think it needs a lot, should do us for now.

**Pull request merged**
